### ISSUE TITLE
Compatibility with unittest

### ISSUE THREAD

**Issue by claudep** [bitmazk/django-calendarium#27]
I don't know well the nose test system, but currently calendarium tests are not run in a standard Django project because test files do not start with "test" (i-e. forms_tests.py should be test_forms.py). Would it be possible to just change the naming of these files to allow for better discovery, or would other things break if not using nose?

**Comment by dkaufhold** [comment]
You can test the app on its own by following the contribution steps described here https://django-calendarium.readthedocs.org/en/latest/contribute.html

To sum it up, you would then create a virtual env for the app itself and use the app's own test command, which will then use nose.

**Comment by claudep** [comment]
Sure, I've seen that, however I'd like to know if it is possible to add support for standard Django project testing by renaming test files, without breaking nose testing method.
