### ISSUE TITLE
delete_period fails on Django 1.7

### ISSUE THREAD

**Issue by claudep** [bitmazk/django-calendarium#29]
In Django 1.7, unsaved models are not hashable any more (https://docs.djangoproject.com/en/1.7/ref/models/instances/#django.db.models.Model.__hash__), so the following line fails with the error TypeError("Model instances without primary key value are unhashable"):
```
occs = list(set([occ for occ in gen]))
```
if there are dynamic occurrences in the list. What was the aim of this "deduplication" line in the origin (introduced in db7e6c3ba3)?

**Comment by Tyrdall** [comment]
@claudep Mhm, I'm not sure why I removed them. Seems the ``get_occurrences`` created some. Happened a long time ago =) Have you tried removing it and running the tests?

**Comment by Tyrdall** [comment]
Fixed in v1.2.
