### ISSUE TITLE
'EventModelManager' object has no attribute 'get_query_set'

### ISSUE THREAD

**Issue by BobBowles** [bitmazk/django-calendarium#33]
I'm not sure if this is because I am doing something naive/stupid, but I just pointed my browser at the 'calendar' url in my otherwise empty project to try to see a calendar, and it came back with this traceback ([full listing on dpaste.com](http://dpaste.com/268RRNS)), complaining about line 72 in calendarium/models.py.

As you have probably worked out by now I am new to Django, but my thought is usually view classes have a `get_queryset` method. Is this as simple as being a typo? Or, (maybe more likely) do I need to do something (add some event objects?) before I can see a calendar?

**Comment by Tyrdall** [comment]
@BobBowles Don't worry, you are just right. The problem is that we haven't used this app in our own projects for a very long time. I guess the last time we used it, Django 1.5 was state-of-the-art, so another issues might pop up soon =)

Here's a backwards compatible solution for your current issue. Are you willing to work this one out and send a pull request. That would be awesome. If not I can update the app next week.

**Comment by BobBowles** [comment]
I'll try. To date I have only ever posted to my own projects on github, so bear with me, but I should be able to do that before next week. I need to figure out some aspects of git I have never needed to use before. Also, a quick scan of that link you gave makes 1.5->1.8 compatibility look a lot more of a head-scratch than fixing a typo. 

(BTW I also noticed several 1.9 compatibility warnings during migrate and using the runserver;)

**Comment by BobBowles** [comment]
I came across another traceback I don't understand trying to run the test suite. It complains about there being no `factory` module at line 2 in tests/test_app/models.py. Is there some other module I need to install for the tests?

(I already have tox and django-nose).

**Comment by mbrochh** [comment]
Please create a virtual environment and then install `pip install -r requirements.txt`

You can learn more about virtualenv and virtualenvwrapper here: https://virtualenvwrapper.readthedocs.org

**Comment by Tyrdall** [comment]
@mbrochh is right. This is what you need: https://github.com/bitmazk/django-calendarium/blob/master/requirements.txt#L16

**Comment by BobBowles** [comment]
I'll try. To date I have only ever posted to my own projects on github, so bear with me, but I should be able to do that before next week. I need to figure out some aspects of git I have never needed to use before. Also, a quick scan of that link you gave makes 1.5->1.8 compatibility look a lot more of a head-scratch than fixing a typo. 

(BTW I also noticed several 1.9 compatibility warnings during migrate and using the runserver;)

**Comment by BobBowles** [comment]
I have done the fix, and added it to a new branch in my fork in three commits. The reason for 3 commits is I found another issue with Django 1.8 compatibility in the test environment, and I fixed that, too. (Also I added my good self to 'authors' in a separate commit - seems cheeky for <10 lines of code...)

PLEASE NOTE: I have been unable to make tox play ball so I jury-rigged the test environment so I could check it worked. The jury-rigs have NOT been checked in. BUT PLEASE TEST THIS BEFORE YOU MERGE WITH MASTER - or please explain how I can get tox working... (the issue here seems to be the python 2.6 and 2.7 environments  generated errors, and tox hated my 3.4 install so much it bricked.) 

Manually setting up the environments worked for me, BUT I found Django 1.8 seems to need newer versions of the other dependencies, particularly django-filer.

Environments tested:
python2.7 / Django 1.5
python2.7 / Django 1.8
python3.4 / Django 1.8

**Comment by BobBowles** [comment]
I don't know if this helps, but I wrote the notes below on my development/testing procedures.

Problems With Tox
=================

I could not get tox to work.
 
Part of the problem was it seemed to be unable to find the appropriate libraries for setting up the 3.x environments I added. This seems to be the same reason that virtualenv failed for 3.x. 

The other part of the problem was that the 2.x environments all gave tracebacks after failing to run, so I gave up with tox and settled for testing the specific problems I was looking at.


Procedure For My Jury-Rig Tests
===============================

I conducted development and testing in the following environments:
python2.7 + Django 1.5; python2.7 + Django 1.8; python3.4 + Django 1.8

In all cases I established the test environments and conducted the tests in the following way:

Create the test environment:
----------------------------

	1)   make the Python environment:
	     *    for python2.7 > virtualenv py27-djXY
	     *    for python3.4 > python3.4 -m venv py34-djXY
	     (these seemed to be mutually exclusive between Python2 and Python3 - see discussion of tox).
	2)   activate the environment:
	     > source pyMN-djXY/bin/activate
	3)   ensure pip is up to date:
	     > pip install --upgrade pip
	4)   install the baseline requirements from requirements.txt:
	     > pip install -r requirements.txt
	5)   install django.
	     *    for django-1.5:
	          > pip uninstall django
	          > pip install django==1.5
	     *    for django-1.8:
	          > pip install --upgrade django-filer
	          (this upgrades Django to 1.8 and upgrades some other dependencies too).
	6)   Record the module configuration:
	     > pip freeze > requirements-pyMN-djXY.txt
	7)   Configure a physical sqlite database file in test_settings.py (named db.pyMN-djXY)
	8)   make the database tables:
	     > ./manage.py syncdb

Development/Test Cycle:
-----------------------

	9)   Switch between environments as required:
	     > deactivate
	     > source pyMN-djXY/bin/activate
	     > edit the database name in test_settings.py to db.pyMN-djXY
	10)  run the server:
	     > ./manage.py runserver
	11)  Conduct dynamic code/configuration changes and observe the effect in a browser pointed at http://localhost:8000/

Differences in Module Version Requirements
==========================================

These are notes on the differences in module requirements across the matix of Python and Django versions I tested.

Python 2.7 Django 1.5 -> 1.8
----------------------------

The main difference (apart from Django itself) is django-filer (0.9.5 -> 0.9.11) which pulls in upgrades for a couple of other dependencies (django-mptt 0.5.5 -> 0.7.4, Pillow 2.4.0 -> 2.9.0) with an additional requirement for Unidecode 0.4.18.

Django 1.8 Python 2.7 -> 3.4
----------------------------

The dependencies for Django 1.8 between Python versions 2.7 and 3.4 are basically the same. Python 3.4 has fewer dependencies (no need for funcsigs or wheel), probably because these have been assimilated into the main language.

**Comment by Tyrdall** [comment]
@BobBowles Awesome! Thanks a lot. I pushed some small tweaks: https://github.com/bitmazk/django-calendarium/commit/50f8b0047dea1d8d5ad836df9b15fd73e7b00237
