### ISSUE TITLE
ImproperlyConfigured at /calendar/event/create/

### ISSUE THREAD

**Issue by BobBowles** [bitmazk/django-calendarium#35]
Trying to create a new event from the basic monthly calendar, I obtained the following exception in the browser:

    ImproperlyConfigured at /calendar/event/create/
    Using ModelFormMixin (base class of EventCreateView) without the 'fields' attribute is prohibited.

(full traceback [here](http://dpaste.com/0Y0SQDF))

This seems to be related to a recent change in Django (see [Django ticket](https://code.djangoproject.com/ticket/21753)).

I'm not sure if this means I need to add something to the settings, or whether (as seems likely) this is another compatibility issue regarding Django 1.8.

**Comment by Tyrdall** [comment]
@BobBowles Yes, since we don't use custom forms for some views we need to define fields. Fixed it here: https://github.com/bitmazk/django-calendarium/commit/edfb4e090a74650d75d7793048d5ff4624f52371#diff-5912bddbae629868b93112119c9cd485R264

**Comment by BobBowles** [comment]
Ty Tobias I will try it out in the morning.
