### ISSUE TITLE
AttributeError at /calendar/2015/7/

### ISSUE THREAD

**Issue by BobBowles** [bitmazk/django-calendarium#36]
Python3.4.3 environment with current Django 1.8.3.

Error message:

    AttributeError at /calendar/2015/7/
    'generator' object has no attribute 'next'

Full traceback is posted [here](http://dpaste.com/0DNNADM)

Steps to reproduce:

1. Start server with an empty database, point a browser at `http://localhost:8000/calendar`. An empty calendar for the current month is displayed, with some navigation controls.
2. Click on `Create an Event`, then fill out the event details for an event in the current month.
3. Navigate back to the calendar. The traceback is displayed.

When I looked this up on Google I found several discussions of Python2 vs. Python3 treatment of generators (useful-looking discussions on Stack Exchange: [Co-routines in Python3](http://stackoverflow.com/questions/21622193/python-3-2-coroutine-attributeerror-generator-object-has-no-attribute-next), and [No next() function in Python3](http://stackoverflow.com/questions/12274606/theres-no-next-function-in-a-yield-generator-in-python-3), also this note on [Python2 vs. Python3 differences](http://programeveryday.com/post/differences-between-python-27x-and-python-3x/))

So, this looks to me like a Python2-Python3 compatibility issue ([PEP 3114](https://www.python.org/dev/peps/pep-3114/)), and if that is the case the solution _should_ be straightforward :) If I'm right the solution should look something like this in `calendarium/models.py`, line 251:

    --         occ = occurrence_gen.next()
    ++         occ = next(occurrence_gen)

and this will also 'just work' in Python2.6+

(Personal note: It may not seem like it but the last couple of issues I raised have moved things forward. I hope this one does, too. I'm kind of enjoying getting involved...)

**Comment by BobBowles** [comment]
I have started work on this, if you can live with my micky-mouse testing...

**Comment by BobBowles** [comment]
Checked in the fix to my py34-dj18 branch https://github.com/BobBowles/django-calendarium/commit/e3d1a1efe1b37c9b710201e88f4ce7b017e56637

I have sent you a puul request.

**Comment by Tyrdall** [comment]
Well @BobBowles thanks again =) Everything's great, your contribution is awesome. Unfortunately we're not using this app in production anymore, so I'm very very grateful for everyone who takes the time to push it forward!

Released v1.3.1: https://pypi.python.org/pypi/django-calendarium/1.3.1
