### ISSUE TITLE
Results of compatibility tests

### ISSUE THREAD

**Issue by BobBowles** [bitmazk/django-calendarium#42]
I found a couple more issues with PEP3114 and PEP469 to do with handling of generators and iterators and fixed those in my py34-dj18 branch. The current state of play is summarised thus:

Summary
-------

The pass/fail matrix currently looks like this:

    py\dj   |  1.5  |  1.6  |  1.7  |  1.8  |
    -----------------------------------------
    2.6     |   X   |   X   |   X   |   X   |
    2.7     |   X   |  PASS |  PASS |  PASS |
    3.2     |   X   |   X   |   X   |   X   |
    3.4     |  PASS |  PASS |  PASS |  PASS |
    -----------------------------------------

With Django 1.5 the only Python that works in testing is 3.4. The others fail with problems parsing commandline arguments to manage.py. (In production they _may_ still be OK).

Python2.6 failed comprehensively due to issues with python syntax in dependencies. This looks like it is not just end-of-life, but deceased. It is a dead Python, it is no more...

Python 3.2 failed comprehensively due to problems parsing statement(s) in calendarium/widgets.py. I will take a look at this to see if I can find an improved way of writing the code. This _may_ enable running under Django >= 1.6.

Python 3.4 passed with _all_ versions of Django tested.

Conclusion
----------

Python 2.6 is off the menu.

Django-calendarium currently works for combinations of Python2.7 and Python3.4+ and for Django >=1.6.

Currently django-calendarium is broken under Python3.2, but this may be fixable with a simple syntax change. 

With the exception of Python3.4, django-calendarium no longer works in testing for Django 1.5. The issue appears to be compatibility of commandline arguments in manage.py that prevent tests from running, and may not reflect usage in production.

Actions
-------

Investigate Python3.2 problems with syntax and string handling.

I will hang fire on sending a pull request until I have had a closer look at the issues with Python3.2.

**Comment by BobBowles** [comment]
The problem lay in Python3.2 handling of Unicode strings. I changed the unicode specifier on the string, and changed the method of formatting to align with PEP3101.

Summary
-------

The pass/fail matrix now looks like this:

    py\dj   |  1.5  |  1.6  |  1.7  |  1.8  |
    -----------------------------------------
    2.6     |   X   |   X   |   X   |   X   |
    2.7     |   X   |  PASS |  PASS |  PASS |
    3.2     |   X   |  PASS |  PASS |  PASS |
    3.4     |  PASS |  PASS |  PASS |  PASS |
    -----------------------------------------

Provided Python2.6 and Django 1.5 can be regarded as end-of-life I think that's about as good as it gets.

**Comment by Tyrdall** [comment]
Again, great work! I changed the requirements to ``Django>=1.6``. I will add your great matrix to the README. Please let me know, if you want me to push a new version to PyPI.

**Comment by BobBowles** [comment]
For my own needs I can install from source, but the compatibility matrix only really applies to the latest version, so someone installing from PyPi won't have access to that unless you push a new package there. Of course maybe it's an idea to wait a day or two in case I find something else ;)

**Comment by Tyrdall** [comment]
@BobBowles Will do!
