### ISSUE TITLE
__unicode__ does not work on python 3.5

### ISSUE THREAD

**Issue by annerajb** [bitmazk/django-calendarium#46]
Hello,

Could it be possible to add to the models a __str__ method since in python 3.5 __unicode__ does not work?

**Comment by Tyrdall** [comment]
@annerajb Sure! Feel free to post a full request.

**Comment by Tyrdall** [comment]
@annerajb Thanks!

**Comment by annerajb** [comment]
When will this be released to be used available on pip?

**Comment by Tyrdall** [comment]
https://pypi.python.org/pypi/django-calendarium

Done!
