### ISSUE TITLE
South migration failed - MySQL using utf8mb4

### ISSUE THREAD

**Issue by drfraser** [bitmazk/django-calendarium#48]
My website is using utf8mb4 as the character set and when I migrated the tables (South, Django 1.6), MySQL complained:

_mysql_exceptions.Warning: Specified key was too long; max key length is 767 bytes

due to the 'slug' column added in 0009_auto__add_field_eventcategory_slug.py.  All 255 characters are being used as part of the key that is created and so that overruns MySQL's 767 limit (255 * 4).

But the charset used in this database is utf8.. which should have been ok. And MySQL added the column anyway, but South bailed because it did not like the warning.

I manually fixed South's migration history and got migration 0010 to work so no problems are anticipated. I just wanted to submit the issue for anyone else who might run into this.

**Comment by Tyrdall** [comment]
@drfraser Can you paste the exact error?

We haven't been using mysql for years, so maybe you're able to figure out what to do and to come up with a pull request or a possible solution.

**Comment by drfraser** [comment]
Sorry, I submitted the report inadvertently. It's not a big issue but more an artifact of my setup and of course MySQL's limitations...

**Comment by Tyrdall** [comment]
Ah great, thanks for the explanation. :)
