### ISSUE TITLE
Python3+ 'EventCategory' object has no attribute 'title'

### ISSUE THREAD

**Issue by 06GitHub** [bitmazk/django-calendarium#50]
Hello,
First, many thanks for your great application django-calendarium ! It provides both nice functions and nice templates (specially the monthly calendar which is graphically very nice) .

I think there is a typo in file models.py :

class EventCategory(models.Model):
[...]
    def __str__(self):
        return self.title

Should read :
class EventCategory(models.Model):
[...]
    def __str__(self):
        #return self.title
        return self.name

in order to prevent error "'EventCategory' object has no attribute 'title'" with Python 3+.

Thks again.

**Comment by dkaufhold** [comment]
@06GitHub Thanks for pointing it out!

I've fixed the attribute and released a new version (1.3.3) to PyPI.
