### ISSUE TITLE
New release for Django 1.9

### ISSUE THREAD

**Issue by PabloCastellano** [bitmazk/django-calendarium#52]
Commit https://github.com/bitmazk/django-calendarium/commit/29bf141ff4a7d12793225977ba797f7d5faf0faa replaces `django.contrib.contenttypes.generic` which is deprecated in Django 1.9.

Version in pypi is 1.3.3 which doesn't include this commit. Please, could you upload a new version to pypi?

Thanks!

**Comment by Tyrdall** [comment]
Done! 1.3.4

**Comment by PabloCastellano** [comment]
Thanks for being so fast!
