### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by vinamelody** [bitmazk/django-calendarium#56]
Hi, I am getting this when using Python 3

`/Users/vinamelody/Envs/mycalendar/lib/python3.5/importlib/__init__.py:126: RemovedInDjango110Warning: django.core.context_processors is deprecated in favor of django.template.context_processors.
  return _bootstrap._gcd_import(name[level:], package, level)`

**Comment by Tyrdall** [comment]
@vinamelody This is not a calendarium issue.

As the error message says, simply replace all ``django.core.context_processors``with ``django.template.context_processors``.
