### ISSUE TITLE
No support for Events that last over x days?

### ISSUE THREAD

**Issue by 10featj** [bitmazk/django-calendarium#58]
I cant seem to get an event to span over a multiple days it is occurring on, for example if an event lasted 3 days back to back can i get the event in each day?

**Comment by Tyrdall** [comment]
@10featj Should be possible. How are you creating that event and how is it displayed?

**Comment by 10featj** [comment]
I have not changed much in the code on the project, should it be able to load the event on each page it's on straight from installation?

**Comment by Tyrdall** [comment]
Sure :)
So, you created an event, which lasts 3 days, but it doesn't show up on the calendar?

**Comment by 10featj** [comment]
It will only show up on the first day on the month view, it shows fine on the day views. Sorry i should have been clearer

**Comment by Tyrdall** [comment]
You're right. The following commit should fix it: https://github.com/bitmazk/django-calendarium/commit/9e6b6af771568778fc0ea360970f94e65166bde0

**Comment by 10featj** [comment]
Thank you so much! i downloaded this not to long ago, when did the commit get released? Makes me think if i am missing any other features :+1:

**Comment by Tyrdall** [comment]
This commit isn't included in the latest package. You can install the current state by using:

``pip install -e git+https://github.com/bitmazk/django-calendarium.git#egg=calendarium

**Comment by 10featj** [comment]
Beautiful, the commit worked perfectly! Thank you

**Comment by 10featj** [comment]
I have just gone back into the calendar date view after this fix and i get the same event repeated but starting on different days 

For example if i set an event up on 6th to end on the 10th if i click on the day view on the 6th i will have one event, if i click it on the 7th i will have two events one from the 6th to the 10th and one from 7th to the 10th.

How could i stop this from happening

**Comment by Tyrdall** [comment]
@10featj This new fix should do it: https://github.com/bitmazk/django-calendarium/commit/cabe69eff965dff80893012fb4dfe724e995807a

**Comment by 10featj** [comment]
Once again it worked fine! Thank you. 

Oh one more thing before i edit the last bits, do you have a system where the user can click on the date within the Month view and be sent to a create new event page with the dates already in?
 Or any other dynamic way of picking dates and times for event? No point re-creating the wheel right :)

Haha thanks J.

**Comment by Tyrdall** [comment]
@10featj You're welcome.

Mhm, no we didn't add something like this, I'm sorry. To be honest, we stopped working with this app years ago. Currently we don't have an active project, which makes use of it :) Anyway, feel free to fork the app and to push some pull requests, if you want to.

**Comment by 10featj** [comment]
ahh okay, Thank you for you help once again!

**Comment by 10featj** [comment]
Back again! haha, As we sorted out printing the same event on multiple days there seems to be a problem with the data. Each event that is printed has a different end date but its the same event its like its being +1 every time its being printed or looped through. Sorry to bother you again. Just thought i would check if you already have a piece of code that could fix this. Thanks J

**Comment by Tyrdall** [comment]
Oh dear :) Unfortunately I always have to find the relevant part in the code, since it's been too long since we used this app. We made use of generators and now I'm not sure, if this is the right way. I would love to refactor the whole thing, but currently I don't have the time to create anything big here.

Are you able to fork this app and create and solution yourself?

**Comment by 10featj** [comment]
I have been trying but i cant seem to find the cause of it, i don't know where to look. It just seems to be adding +1 to the end and start date of the event as its being shown on each day. It's like there is a loop printing and adding one to the start/end date every time its printed to the month view.
